version: '3.8'

services:
  postgres:
    container_name: db-nest-clean
    image: postgres:16.2-alpine3.19
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=nest-clean
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - nest-clean-network
  
  redis:
    container_name: nest-clean-cache-redis
    image: redis:alpine3.20
    ports:
      - 6379:6379
    networks:
      - nest-clean-network
    volumes:
      - db:/var/lib/redis/data

  nest-clean:
    build: 
      context: .
    container_name: 05-nest-clean
    ports:
      - 3333:3333
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_HOST${REDIS_HOST}
      - JWT_PUBLIC_KEY=${JWT_PUBLIC_KEY}
      - JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY}
      - CLOUDFLARE_ACCOUNT_ID=${CLOUDFLARE_ACCOUNT_ID}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    depends_on:
      - postgres
      - redis
    networks:
      - nest-clean-network

networks:
  nest-clean-network:
    name: nest-clean-network
    external: true
    driver: bridge

volumes:
  db: