name: CI

on:
  push:
    branches: 
      - main  

jobs:
  build:
    name: 'Build and Push'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 9
  
      - run: pnpm install  
      - run: pnpm test