name: CI

on:
  push:
    branches: 
      - main  

jobs:
  build:
    name: 'Build and Push'
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node: [ 16, 18, 20 ]

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Setup node 
        uses: actions/setup-node@v4
        with:
          # node-version: ${{ matrix.node}}
          node-version: 20
          # cache: 'pnpm'
  
      - run: pnpm install && pnpm test

      - name: Generate tag
        id: generate_tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Login into the container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: pedrojorge148/05-nest-clean:${{ steps.generate_tag.outputs.sha }},pedrojorge148/05-nest-clean:latest

      # - name: Build docker image
      #   run: docker build -t pedrojorge148/05-nest-clean:${{ steps.generate_tag.outputs.sha }} .

      # - name: Push image
      #   run: |
      #     docker push pedrojorge148/05-nest-clean:${{ steps.generate_sha.outputs.sha }}
      #     docker tag pedrojorge148/05-nest-clean:${{ steps.generate_sha.outputs.sha }} pedrojorge148/05-nest-clean:latest
      #     docker push pedrojorge148/05-nest-clean:latest
